### PR TITLE
Fix Rails 4.1 compatibility.

### PR DESCRIPTION
**Pull request by lowjoel**

### CODE REVIEW

**Comment by asgeo1** [comment]
Please merge!

**Comment by lowjoel** [comment]
@nilesh #2 and this PR both fixes the same thing. Please merge this soon.

**Comment by booleanbetrayal** [comment]
:+1: Please merge!

**Comment by hlascelles** [comment]
+1

**Comment by CyborgMaster** [comment]
Now that this is merged, can we get a release to RubyGems?

**Comment by tknarr** [comment]
There's an unofficial copy with the Rails 4 fix at:
https://rubygems.org/gems/rails4_before_render
taken from PR #6

**Comment by CyborgMaster** [comment]
@tknarr, I'm actually using your branch right now.  I was hoping we might get the official version updated.

**Comment by booleanbetrayal** [comment]
just built and pushed in v0.1.39!

**Pull request merged**
